const IndicatorFactory = {
  atr: require("./atr"),
  adx: require("./adx"),
  ao: require("./ao"),
  bb: require("./bb"),
  cci: require("./cci"),
  chi: require("./chi"),
  kst: require("./kst"),
  macd: require("./macd"),
  roc: require("./roc"),
  rsi: require("./rsi"),
  sma: require("./sma"),
  kd: require("./kd"),
  trix: require("./trix"),
  ema: require("./ema"),
  wma: require("./wma"),
  wema: require("./wema"),
  wr: require("./wr"),
  ichimoku: require("./ichimoku"),

  // candle sticks
  abandonedbaby: require("./candleStick/abandonedbaby"),
  bearishengulfingpattern: require("./candleStick/beeb"),
  bullishengulfingpattern: require("./candleStick/bueb"),
  darkcloudcover: require("./candleStick/darkcloudcover"),
  downsidetasukigap: require("./candleStick/downsidetasukigap"),
  doji: require("./candleStick/doji"),
  dragonflydoji: require("./candleStick/dragonflydoji"),
  gravestonedoji: require("./candleStick/gravestonedoji"),
  bullishharami: require("./candleStick/bullishharami"),
  bearishharamicross: require("./candleStick/bearishharamicross"),
  bullishharamicross: require("./candleStick/bullishharamicross"),
  bullishmarubozu: require("./candleStick/bullishmarubozu"),
  bearishmarubozu: require("./candleStick/bearishmarubozu"),
  eveningdojistar: require("./candleStick/eveningdojistar"),
  eveningstar: require("./candleStick/eveningstar"),
  bearishharami: require("./candleStick/bearishharami"),
  piercingline: require("./candleStick/piercingline"),
  bullishspinningtop: require("./candleStick/bullishspinningtop"),
  bearishspinningtop: require("./candleStick/bearishspinningtop"),
  morningdojistar: require("./candleStick/morningdojistar"),
  morningstar: require("./candleStick/morningstar"),
  threeblackcrows: require("./candleStick/threeblackcrows"),
  threewhitesoldiers: require("./candleStick/threewhitesoldiers"),
  bullishhammer: require("./candleStick/bullishhammer"),
  bearishhammer: require("./candleStick/bearishhammer"),
  bullishinvertedhammer: require("./candleStick/bullishinvertedhammer"),
  bearishinvertedhammer: require("./candleStick/bearishinvertedhammer"),
  hammer: require("./candleStick/hammer"),
  hammerunconfirmed: require("./candleStick/hammerpatternunconfirmed"),
  hangingman: require("./candleStick/hangingman"),
  hangingmanunconfirmed: require("./candleStick/hangingmanunconfirmed"),
  shootingstar: require("./candleStick/shootingstar"),
  shootingstarunconfirmed: require("./candleStick/shootingstarunconfirmed"),
  tweezertop: require("./candleStick/tweezertop"),
  tweezerbottom: require("./candleStick/tweezerbottom"),
};

module.exports = IndicatorFactory;
